---
- name: install Mongo
  hosts: all
  become: true
  tasks:
    - name: add apt key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: add apt repo
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        
    - name: Install mongo package
      apt:
        name: mongodb-org
        state: present
        
    - name: Enable mongo
      systemd: name=mongod enabled=yes
