---
- name: install App prereq 
  hosts: all
  become: true
  tasks:
    - name: install ruby & bundler
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - ruby-full
        - ruby-bundler
        - build-essential
      